Add basic support for catch2
pahdolabs/godot pull request #14
Opened 2023-05-15 22:41 UTC by alex-pahdo

A new scons option `build_custom_tests` decides whether to include the Catch2 library and related code in the build.

A new Godot executable option `--test-external` tells Godot to run tests

WIP--other platform main() files and a message when setting the flag without the test build

2023-05-15 22:45 UTC, Razoric480 reviewed
Is the lack of change to godot_windows.cpp and godot_x11.cpp intentional or reserved for later?

2023-05-15 22:46 UTC, Razoric480 commented
Nevermind I can't read

2023-05-15 23:11 UTC, alex-pahdo commented
I had meant to keep it as a draft until I added the WIP stuff, but I can't read either

2023-05-16 01:15 UTC, Razoric480 requested changes
```
godot_windows.cpp
platform\windows\godot_windows.cpp(181): error C2664: 'void run_catch_tests(int,char **)': cannot convert argument 2 from 'wchar_t **' to 'char **'
platform\windows\godot_windows.cpp(181): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
C:\h0\godot\src\godot\main/tests/catch_testing.h(12): note: see declaration of 'run_catch_tests'
platform\windows\godot_windows.cpp(181): note: while trying to match the argument list '(int, wchar_t **)'
scons: *** [platform\windows\godot_windows.windows.opt.tools.64.obj] Error 2
```

2023-05-16 03:03 UTC, Razoric480 commented
I got it to build with 
```c++
char buffer[1024];
wcstombs(buffer, *argv, sizeof(buffer));
char *buffer_start = &buffer[0];
run_catch_tests(argc, &buffer_start);
```
it's a bit messy looking. maybe we should alloc a heap so that it's the right size. should also probably use `wcstombs_s()` instead

2023-05-16 03:08 UTC, Razoric480 commented
Actually argv_utf8 is already delcared, so we cna just use it
```c++
run_catch_tests(argc, &argv_utf8[0]);
```

2023-05-16 03:10 UTC, Razoric480 commented
Instead faced with a linker error: `LINK : fatal error LNK1181: cannot open input file 'Catch2d.lib.windows.opt.tools.64.lib'`

2023-05-16 03:22 UTC, Razoric480 commented
Got it to link by replacing `env_base.Append(LIBS=["Catch2d.lib"])` with `env_base.Append(LINKFLAGS=["Catch2d.lib"])` (inspired by modules/raycast's SCsub), but then I get
```
Catch2d.lib(catch_clara.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_clara.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_session.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_session.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_string_manip.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_string_manip.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_textflow.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_textflow.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_commandline.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_commandline.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_test_spec.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_test_spec.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_random_seed_generation.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_random_seed_generation.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_console_colour.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_console_colour.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_config.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_config.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_source_line_info.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_source_line_info.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_reusable_string_stream.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_reusable_string_stream.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_enforce.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_enforce.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_list.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_list.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_test_case_info.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_test_case_info.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_registry_hub.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_registry_hub.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_run_context.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_run_context.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_version.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_version.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_startup_exception_registry.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_startup_exception_registry.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_test_case_registry_impl.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_test_case_registry_impl.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_interfaces_reporter.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_interfaces_reporter.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_reporter_multi.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_reporter_multi.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MT_StaticRelease' in godot_windows.windows.tools.64.obj
Catch2d.lib(catch_reporter_registry.obj) : error LNK2038: mismatch detected for '_I [...]

2023-05-16 03:23 UTC, alex-pahdo commented
> Instead faced with a linker error: `LINK : fatal error LNK1181: cannot open input file 'Catch2d.lib.windows.opt.tools.64.lib'`

that's weird, because it seems like a LIBSUFFIX problem, but I would expect to see the same problem on unix

2023-05-16 03:31 UTC, alex-pahdo commented
Don't dig too much into it tonight, since we can work it out online tomorrow, but it looks like maybe Catch2 just has to be built with the same settings.
https://stackoverflow.com/a/7668644/21169548


Worst case scenario, we just use the amalgamated release (single header/cpp pair, plug directly into sources list)

2023-05-16 03:55 UTC, Razoric480 commented
Got it to build.

I had to go into the generated visual studio project for Catch2 and switch it to:
A- Build a release build (`Catch2.lib`)
B- Use the Multi-Threaded Runtime library (and not Multi-Threaded DLL which was the default)

I also had to go into SConstruct and change the lib append to:
```python
env_base.Append(LIBS=[File("C:\\Program Files (x86)\\catch2\\lib\\Catch2.lib")])
```

2023-05-16 04:09 UTC, Razoric480 commented
- Cmake will need to have its CMAKE_CXX_FLAGS_RELEASE changed from `/MD /O2 /Ob2 /DNDEBUG` to `/MT /O2 /Ob2 /DNDEBUG` when building the catch2 project for windows
- Cmake needs to build and install the release library and not the debug one.

2023-05-16 19:18 UTC, Razoric480 requested changes

2023-05-16 19:18 UTC, Razoric480 commented on SConstruct
> +		env_base.Append(LIBS=[File("Catch2d.lib")])
File requires a relative or absolute path, so it'd be `File("C:\\Program Files (x86)\\catch2\\lib\\Catch2.lib")`

also removing the `d` from Catch2 since we're using the release build

2023-05-16 19:23 UTC, alex-pahdo commented
Oh I forgot to remove the `d`

2023-05-16 19:23 UTC, alex-pahdo commented on SConstruct
> +		env_base.Append(LIBS=[File("Catch2d.lib")])
*TF2 Administrator voice*

 wow, that was fast

2023-05-16 19:24 UTC, Razoric480 commented
> Oh I forgot to remove the `d`

You're throwing a low ball there

2023-05-16 19:33 UTC, Razoric480 approved these changes
![image](https://github.com/pahdolabs/godot/assets/2823241/2f95c2a5-8818-4e57-ba14-88351bd1989a)

it works, but that fatal error is weird

2023-05-16 19:57 UTC, merged